#!/usr/bin/env bash
set -euo pipefail

INTEGRATION_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
API_DIR="$(cd "${INTEGRATION_DIR}/../.." && pwd)"

# shellcheck source=./lib.sh
source "${INTEGRATION_DIR}/lib.sh"

cd "${API_DIR}"

PORT="${CROLENS_TEST_PORT:-8787}"
BASE_URL="http://127.0.0.1:${PORT}"

RPC_PORT="${CROLENS_TEST_MOCK_RPC_PORT:-19000}"
MOCK_RPC_URL="http://127.0.0.1:${RPC_PORT}"

JSONRPC_LIMIT="${CROLENS_TEST_JSONRPC_LIMIT:-5}"
JSONRPC_WINDOW_SECS="${CROLENS_TEST_JSONRPC_WINDOW_SECS:-60}"

DEV_VARS_FILE="${API_DIR}/.dev.vars"
DEV_VARS_BACKUP="${API_DIR}/.dev.vars.integration.bak"

WRANGLER_CONFIG="${CROLENS_TEST_WRANGLER_CONFIG:-}"
SKIP_D1_INIT="${CROLENS_TEST_SKIP_D1_INIT:-0}"
WRANGLER_CONFIG_ARG=()

if [[ -n "${WRANGLER_CONFIG}" ]]; then
  if [[ "${WRANGLER_CONFIG}" != /* ]]; then
    WRANGLER_CONFIG="${API_DIR}/${WRANGLER_CONFIG}"
  fi
  WRANGLER_CONFIG_ARG=(-c "${WRANGLER_CONFIG}")
  echo "[integration] Using wrangler config: ${WRANGLER_CONFIG}"
fi

echo "[integration] Using BASE_URL=${BASE_URL}"
echo "[integration] Using MOCK_RPC_URL=${MOCK_RPC_URL}"
echo "[integration] Using state dir: ${STATE_DIR}"

mkdir -p "${API_DIR}/.wrangler"
rm -rf "${STATE_DIR}"
mkdir -p "${STATE_DIR}"

if [[ -f "${DEV_VARS_FILE}" ]]; then
  cp "${DEV_VARS_FILE}" "${DEV_VARS_BACKUP}"
else
  rm -f "${DEV_VARS_BACKUP}"
fi

cat > "${DEV_VARS_FILE}" <<EOF
# Generated by tests/integration/setup.sh (do not commit).
BLOCKPI_RPC_URL=${MOCK_RPC_URL}
X402_PAYMENT_ADDRESS=${TEST_PAYMENT_ADDRESS}
X402_TOPUP_CREDITS=1000
CORS_ALLOW_ORIGIN=*
RATE_LIMIT_JSONRPC_PER_MIN=${JSONRPC_LIMIT}
RATE_LIMIT_JSONRPC_WINDOW_SECS=${JSONRPC_WINDOW_SECS}
EOF

if [[ "${SKIP_D1_INIT}" != "1" ]]; then
  echo "[integration] Initializing D1 schema + seeds..."
  npx wrangler d1 execute crolens-db --local --persist-to "${STATE_DIR}" --file=./db/schema.sql -y >/dev/null
  npx wrangler d1 execute crolens-db --local --persist-to "${STATE_DIR}" --file=./db/seed.sql -y >/dev/null
  npx wrangler d1 execute crolens-db --local --persist-to "${STATE_DIR}" --file=./tests/integration/fixtures/seed_test_data.sql -y >/dev/null
else
  echo "[integration] Skipping D1 init (CROLENS_TEST_SKIP_D1_INIT=1)"
fi

echo "[integration] Starting mock RPC server..."
node "${INTEGRATION_DIR}/mock_rpc_server.js" --port "${RPC_PORT}" --fixtures "${INTEGRATION_DIR}/fixtures/rpc_responses.json" \
  >"${STATE_DIR}/mock_rpc.log" 2>&1 &
RPC_PID="$!"

echo "[integration] Starting wrangler dev..."
npx wrangler dev "${WRANGLER_CONFIG_ARG[@]}" --local --persist-to "${STATE_DIR}" --port "${PORT}" --ip 127.0.0.1 --log-level warn --show-interactive-dev-session false \
  >"${STATE_DIR}/wrangler.log" 2>&1 &
WRANGLER_PID="$!"

cat > "${PIDS_FILE}" <<EOF
RPC_PID=${RPC_PID}
WRANGLER_PID=${WRANGLER_PID}
DEV_VARS_BACKUP=${DEV_VARS_BACKUP}
DEV_VARS_FILE=${DEV_VARS_FILE}
BASE_URL=${BASE_URL}
MOCK_RPC_URL=${MOCK_RPC_URL}
EOF

echo "[integration] Waiting for /health..."
for _ in $(seq 1 60); do
  status="$(curl -s -o /dev/null -w "%{http_code}" "${BASE_URL}/health" 2>/dev/null || true)"
  if [[ -n "${status}" && "${status}" != "000" ]]; then
    echo "[integration] Ready (health HTTP ${status})"
    exit 0
  fi
  sleep 1
done

echo "[integration] Failed to start services. Logs:"
echo "---- mock_rpc.log ----"
tail -n 100 "${STATE_DIR}/mock_rpc.log" || true
echo "---- wrangler.log ----"
tail -n 200 "${STATE_DIR}/wrangler.log" || true
exit 1
